import tw, { TwStyle } from 'twin.macro';

import { ColorType } from '@/components/interface';

export const PM_SIZE = {
    none: 0,
    xsmall: 1,
    small: 2,
    medium: 4,
    large: 10,
    xlarge: 20,
} as const;

export const GAP_SIZE = {
    none: 0,
    xsmall: 1,
    small: 2,
    medium: 3,
    large: 4,
    xlarge: 5,
} as const;

export const BG_COLOR: Record<ColorType, TwStyle> = {
    primary: tw`bg-primary`,
    dark: tw`bg-black`,
    error: tw`bg-error`,
    info: tw`bg-blue-300`,
    light: tw`bg-gray-50`,
    secondary: tw`bg-secondary`,
    success: tw`bg-success`,
};

export const FONT_COLOR: Record<ColorType, TwStyle> = {
    primary: tw`text-primary`,
    dark: tw`text-black`,
    error: tw`text-error`,
    info: tw`text-blue-300`,
    light: tw`text-gray-50`,
    secondary: tw`text-secondary`,
    success: tw`text-success`,
};

export const BORDER_COLOR: Record<ColorType, TwStyle> = {
    primary: tw`border-primary`,
    dark: tw`border-black`,
    error: tw`border-error`,
    info: tw`border-blue-300`,
    light: tw`border-gray-50`,
    secondary: tw`border-secondary`,
    success: tw`border-success`,
};

export const TAILWIND_PADDING = {
    all: [
        tw`p-0`,
        tw`p-1`,
        tw`p-2`,
        tw`p-3`,
        tw`p-4`,
        tw`p-5`,
        tw`p-6`,
        tw`p-7`,
        tw`p-8`,
        tw`p-9`,
        tw`p-10`,
        tw`p-11`,
        tw`p-12`,
        tw`p-14`,
        tw`p-16`,
        tw`p-20`,
        tw`p-24`,
        tw`p-28`,
        tw`p-32`,
        tw`p-36`,
        tw`p-40`,
        tw`p-44`,
        tw`p-48`,
        tw`p-52`,
        tw`p-56`,
    ],
    left: [
        tw`pl-0`,
        tw`pl-1`,
        tw`pl-2`,
        tw`pl-3`,
        tw`pl-4`,
        tw`pl-5`,
        tw`pl-6`,
        tw`pl-7`,
        tw`pl-8`,
        tw`pl-9`,
        tw`pl-10`,
        tw`pl-11`,
        tw`pl-12`,
        tw`pl-14`,
        tw`pl-16`,
        tw`pl-20`,
        tw`pl-24`,
        tw`pl-28`,
        tw`pl-32`,
        tw`pl-36`,
        tw`pl-40`,
        tw`pl-44`,
        tw`pl-48`,
        tw`pl-52`,
        tw`pl-56`,
    ],
    right: [
        tw`pr-0`,
        tw`pr-1`,
        tw`pr-2`,
        tw`pr-3`,
        tw`pr-4`,
        tw`pr-5`,
        tw`pr-6`,
        tw`pr-7`,
        tw`pr-8`,
        tw`pr-9`,
        tw`pr-10`,
        tw`pr-11`,
        tw`pr-12`,
        tw`pr-14`,
        tw`pr-16`,
        tw`pr-20`,
        tw`pr-24`,
        tw`pr-28`,
        tw`pr-32`,
        tw`pr-36`,
        tw`pr-40`,
        tw`pr-44`,
        tw`pr-48`,
        tw`pr-52`,
        tw`pr-56`,
    ],
    top: [
        tw`pt-0`,
        tw`pt-1`,
        tw`pt-2`,
        tw`pt-3`,
        tw`pt-4`,
        tw`pt-5`,
        tw`pt-6`,
        tw`pt-7`,
        tw`pt-8`,
        tw`pt-9`,
        tw`pt-10`,
        tw`pt-11`,
        tw`pt-12`,
        tw`pt-14`,
        tw`pt-16`,
        tw`pt-20`,
        tw`pt-24`,
        tw`pt-28`,
        tw`pt-32`,
        tw`pt-36`,
        tw`pt-40`,
        tw`pt-44`,
        tw`pt-48`,
        tw`pt-52`,
        tw`pt-56`,
    ],
    bottom: [
        tw`pb-0`,
        tw`pb-1`,
        tw`pb-2`,
        tw`pb-3`,
        tw`pb-4`,
        tw`pb-5`,
        tw`pb-6`,
        tw`pb-7`,
        tw`pb-8`,
        tw`pb-9`,
        tw`pb-10`,
        tw`pb-11`,
        tw`pb-12`,
        tw`pb-14`,
        tw`pb-16`,
        tw`pb-20`,
        tw`pb-24`,
        tw`pb-28`,
        tw`pb-32`,
        tw`pb-36`,
        tw`pb-40`,
        tw`pb-44`,
        tw`pb-48`,
        tw`pb-52`,
        tw`pb-56`,
    ],
} as const;

export const TAILWIND_MARGIN = {
    all: [
        tw`m-0`,
        tw`m-1`,
        tw`m-2`,
        tw`m-3`,
        tw`m-4`,
        tw`m-5`,
        tw`m-6`,
        tw`m-7`,
        tw`m-8`,
        tw`m-9`,
        tw`m-10`,
        tw`m-11`,
        tw`m-12`,
        tw`m-14`,
        tw`m-16`,
        tw`m-20`,
        tw`m-24`,
        tw`m-28`,
        tw`m-32`,
        tw`m-36`,
        tw`m-40`,
        tw`m-44`,
        tw`m-48`,
        tw`m-52`,
        tw`m-56`,
    ],
    left: [
        tw`ml-0`,
        tw`ml-1`,
        tw`ml-2`,
        tw`ml-3`,
        tw`ml-4`,
        tw`ml-5`,
        tw`ml-6`,
        tw`ml-7`,
        tw`ml-8`,
        tw`ml-9`,
        tw`ml-10`,
        tw`ml-11`,
        tw`ml-12`,
        tw`ml-14`,
        tw`ml-16`,
        tw`ml-20`,
        tw`ml-24`,
        tw`ml-28`,
        tw`ml-32`,
        tw`ml-36`,
        tw`ml-40`,
        tw`ml-44`,
        tw`ml-48`,
        tw`ml-52`,
        tw`ml-56`,
    ],
    right: [
        tw`mr-0`,
        tw`mr-1`,
        tw`mr-2`,
        tw`mr-3`,
        tw`mr-4`,
        tw`mr-5`,
        tw`mr-6`,
        tw`mr-7`,
        tw`mr-8`,
        tw`mr-9`,
        tw`mr-10`,
        tw`mr-11`,
        tw`mr-12`,
        tw`mr-14`,
        tw`mr-16`,
        tw`mr-20`,
        tw`mr-24`,
        tw`mr-28`,
        tw`mr-32`,
        tw`mr-36`,
        tw`mr-40`,
        tw`mr-44`,
        tw`mr-48`,
        tw`mr-52`,
        tw`mr-56`,
    ],
    top: [
        tw`mt-0`,
        tw`mt-1`,
        tw`mt-2`,
        tw`mt-3`,
        tw`mt-4`,
        tw`mt-5`,
        tw`mt-6`,
        tw`mt-7`,
        tw`mt-8`,
        tw`mt-9`,
        tw`mt-10`,
        tw`mt-11`,
        tw`mt-12`,
        tw`mt-14`,
        tw`mt-16`,
        tw`mt-20`,
        tw`mt-24`,
        tw`mt-28`,
        tw`mt-32`,
        tw`mt-36`,
        tw`mt-40`,
        tw`mt-44`,
        tw`mt-48`,
        tw`mt-52`,
        tw`mt-56`,
    ],
    bottom: [
        tw`mb-0`,
        tw`mb-1`,
        tw`mb-2`,
        tw`mb-3`,
        tw`mb-4`,
        tw`mb-5`,
        tw`mb-6`,
        tw`mb-7`,
        tw`mb-8`,
        tw`mb-9`,
        tw`mb-10`,
        tw`mb-11`,
        tw`mb-12`,
        tw`mb-14`,
        tw`mb-16`,
        tw`mb-20`,
        tw`mb-24`,
        tw`mb-28`,
        tw`mb-32`,
        tw`mb-36`,
        tw`mb-40`,
        tw`mb-44`,
        tw`mb-48`,
        tw`mb-52`,
        tw`mb-56`,
    ],
} as const;

export const TAILWIND_GAP = {
    all: [tw`gap-0`, tw`gap-1`, tw`gap-2`, tw`gap-3`, tw`gap-4`, tw`gap-5`],
};
